# Generated by Django 2.0.1 on 2018-01-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180109_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.CharField(default='/static/images/default.png', max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
    ]
