# Generated by Django 2.0.1 on 2018-01-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_comment_best_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
    ]
