# Generated by Django 2.0.1 on 2018-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_article_editors_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_cover',
            field=models.FileField(null=True, upload_to='cover_image'),
        ),
    ]
