# Generated by Django 2.0.1 on 2018-01-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AlterField(
            model_name='article',
            name='favs',
            field=models.IntegerField(default=0),
        ),
    ]
